version = 0.1
[default.deploy.parameters]
stack_name = "template-backend-sam"
resolve_s3 = true
s3_prefix = "template-backend-sam"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "AppEnv=\"dev\""
image_repositories = []